- name: setup Windows Server
  hosts: win

  tasks:
    - name:
      set_fact:
        # Specify the server certificate validation mode (ignore or validate).
        # Ansible defaults to validate on Python 2.7.9 and higher,
        # which will result in certificate validation errors against the Windows self-signed certificates.
        # Unless verifiable certificates have been configured on the WinRM listeners, this should be set to ignore
        ansible_winrm_server_cert_validation: ignore

    - name: install SNMP Service
      win_shell: |
        Install-WindowsFeature SNMP-Service -IncludeAllSubFeature -Verbose

    - name: Ensuring SNMP Trap is started
      win_service:
        name: snmptrap
        state: started

    - name: Ensuring SNMP Service is started
      win_service:
        name: snmp
        state: started

    - name: Replace SNMP communities and managers
      win_snmp:
        community_strings:
          - public
        permitted_managers:
          - 192.168.33.100
        action: set
