- name: setup Ubuntu Server
  hosts: linux
  vars:
    snmpd_packages: 'snmpd'
    snmp_packages: 'snmp'
    snmpd_sysLocation: 'Taiwan'
    snmpd_contact: 'Me <me@example.org>'

    snmpd_clients:
      - 127.0.0.1
      - 192.168.33.20
      - 192.168.33.100
    snmpd_v2_source:
      - 127.0.0.1
      - 192.168.33.0/24
    snmpd_v2_snmpcommunity: public

    snmpd_ipv6: false
    snmpd_loopback_only: false
    snmpd_agentx: false

    ## install also snmpget, snmpwalk...
    snmpd_with_client: false

  tasks:
    - name: Update APT Cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 1800

    - name: Install lsb-release
      become: yes
      apt:
        name: lsb-release

    - name: snmpd package install
      package: name={{ snmpd_packages }} state=present
      when: ansible_system == 'Linux'
      register: pkg_result
      until: pkg_result is success

    - name: snmpd client install
      package: name={{ snmp_packages }} state=present
      when: snmpd_with_client
      register: pkg_result
      until: pkg_result is success

    - name: Update snmpd configuration
      template:
        src: snmpd.conf.j2
        dest: '/etc/snmp/snmpd.conf'
        mode: 0640
        backup: yes
      notify:
        - restart snmpd

    ## https://bugs.launchpad.net/ubuntu/+source/net-snmp/+bug/1246347  "error on subcontainer ‘ia_addr’ insert (-1)"
    - name: suppress buggy snmpd error messages
      replace: dest=/etc/default/snmpd regexp='-Lsd' replace='-LS6d' backup=yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      notify:
        - restart snmpd

    - name: restrict snmpd with hosts.deny
      lineinfile: dest=/etc/hosts.deny line='snmpd:ALL' backup=yes create=yes
    - name: restrict snmpd with hosts.allow
      lineinfile:
        dest: /etc/hosts.allow
        line: "snmpd:{{ item }}"
        backup: yes
        create: yes
      with_items: "{{ snmpd_clients }}"

    - name: ensure service is enabled and started
      service: name=snmpd state=started enabled=yes

  handlers:
    - name: restart snmpd
      service:
        name: snmpd
        state: restarted
