# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", ip: "192.168.33.20"

  config.vm.provider "parallels" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
     sudo apt update
     sudo apt install -y nginx
     sudo apt install -y mysql-server mysql-client
     sudo apt install -y mycli
     sudo apt install -y php-fpm php-mysql
  SHELL
end
