# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provider "parallels" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
     sudo apt update
     sudo apt install -y nginx
     sudo apt install -y mysql-server mysql-client
     sudo apt install -y mycli
     sudo apt install -y php-fpm php-mysql

     #zabbix
     wget https://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.4-1+bionic_all.deb
     sudo dpkg -i zabbix-release_4.4-1+bionic_all.deb
     sudo apt update
     sudo apt -y install zabbix-server-mysql zabbix-frontend-php zabbix-nginx-conf zabbix-agent

     # create db & user
     echo "create database zabbix character set utf8 collate utf8_bin;" > zabbixdb.sql
     echo 'create user zabbix@\`localhost\` identified by "";' >> zabbixdb.sql
     echo "grant all privileges on zabbix.* to zabbix@localhost identified by '';" >> zabbixdb.sql
     sudo mysql -uroot < zabbixdb.sql
     rm zabbixdb.sql
     zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix zabbix
     sudo systemctl restart zabbix-server zabbix-agent nginx php7.2-fpm
     sudo systemctl enable zabbix-server zabbix-agent nginx php7.2-fpm
  SHELL
end
